# Generated by Django 3.0 on 2019-12-11 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toy',
            name='release_date',
            field=models.DateTimeField(),
        ),
    ]
