# Generated by Django 3.0 on 2019-12-17 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfoCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('nombre', models.CharField(default='', max_length=150)),
                ('ingresos_totales', models.IntegerField()),
                ('devoluciones', models.IntegerField()),
                ('ingresos_netos', models.IntegerField()),
                ('rete_fuente', models.IntegerField()),
                ('valor_inven_311217', models.IntegerField()),
                ('valor_inven_311216', models.IntegerField()),
                ('valor_compras_inven_2017', models.IntegerField()),
                ('costo_mercancia_vendida', models.IntegerField()),
                ('honorarios', models.IntegerField()),
                ('impuestos', models.IntegerField()),
                ('arrendamientos', models.IntegerField()),
                ('seguros', models.IntegerField()),
                ('servicios', models.IntegerField()),
                ('gastos_legales', models.IntegerField()),
                ('papeleria_copias', models.IntegerField()),
                ('comisiones', models.IntegerField()),
                ('publicidad', models.IntegerField()),
                ('gastos_nomina', models.IntegerField()),
                ('total_gastos', models.IntegerField()),
                ('realizo_aporte_SS', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ('creado',),
            },
        ),
        migrations.CreateModel(
            name='SeguridadSocial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salud', models.IntegerField()),
                ('pension', models.IntegerField()),
                ('fondo_solidaridad_pensional', models.IntegerField()),
                ('cesantias', models.IntegerField()),
                ('arl', models.IntegerField()),
                ('pension_voluntaria', models.IntegerField()),
                ('afc', models.IntegerField()),
                ('total_aporte', models.IntegerField()),
                ('id_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segurida_social', to='Spec.InfoCompany', verbose_name='SeguridadSocial')),
            ],
            options={
                'verbose_name': 'Aporte',
                'verbose_name_plural': 'Aportes',
                'ordering': ('id_company',),
            },
        ),
    ]
