# Generated by Django 3.0 on 2019-12-17 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Spec', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seguridadsocial',
            options={},
        ),
        migrations.AlterField(
            model_name='seguridadsocial',
            name='id_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguridad_social', to='Spec.InfoCompany', verbose_name='SS'),
        ),
    ]
