# Generated by Django 3.0 on 2019-12-17 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Spec', '0002_auto_20191217_2300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infocompany',
            name='ingresos_netos',
        ),
    ]
