# Generated by Django 3.0 on 2019-12-17 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Spec', '0003_remove_infocompany_ingresos_netos'),
    ]

    operations = [
        migrations.AddField(
            model_name='infocompany',
            name='ingresos_netos',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
